# build libui-ng
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  meson-windows:
    strategy:
      fail-fast: false
      matrix:
        # windows-latest, windows-2022
        os: [windows-latest]
        arch: [x86, x64]
        libtype: [static] # FIXME [static, shared]
        # debug, debugoptimized, release
        buildtype: [debug]
    runs-on: ${{ matrix.os }}
    name: Win-${{ matrix.arch }}-${{ matrix.libtype }}
    steps:
      # Setup build env
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Meson+Ninja
        run: |
          python -m pip install --upgrade pip
          pip install meson ninja
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - name: Meson Setup Build
        shell: cmd
        run: meson setup builddir --backend=vs --buildtype=${{ matrix.buildtype }} --default-library=${{ matrix.libtype }}
      - name: Ninja Build
        run: meson compile -C builddir --verbose
      - name: Run Tests
        run: meson test -C builddir --verbose
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Win-${{ matrix.arch }}-${{ matrix.libtype }}-${{ matrix.buildtype }}
          # lib + header + examples + test + build-log
          path: |
            !builddir/meson-out/*.p/
            builddir/meson-out/libui.*
            ui_windows.h
            ui.h
            builddir/meson-out/*.exe
            builddir/meson-out/*.pdb
            builddir/meson-logs/*.txt
